### ISSUE TITLE
kramdown-rfc-clean-svg-ids reorders some XML attributes

### ISSUE THREAD

**Issue by ajeanmahoney** [cabo/kramdown-rfc#196] opened 2023-05-02 21:48 UTC
Thanks for the kramdown-rfc-clean-svg-ids tool to fix the duplicate SVG ids issue!

When kramdown-rfc-clean-svg-ids is run on an XML file, it does the following in addition to fixing the duplicate ids:

- Changes double quotes around attributes in the <?xml> element to single quotes. 
- Reorders the attributes of the following elements: `<rfc>`, `<author>`, `<date>`, `<xref>`, `<artwork>`, and `<svg>`. For instance, `<artwork type="svg" align="center">` is changed to `<artwork align="center" type="svg">`. 

As there is no affect on output, this isn't really a bug. However, these changes can create noisy diffs, and some authors are sensitive to those.

Could the script be updated to only make updates to ids and to leave the ordering of the XML attributes as is?

**Comment by cabo** [comment] 2023-05-03 20:53
> When kramdown-rfc-clean-svg-ids is run on an XML file, it does the following in addition to fixing the duplicate ids:
> 
> * Changes double quotes around attributes in the <?xml> element to single quotes.

Yes, that is a weird one.  It is a single-line change, so maybe the authors can live with that; otherwise I'll do some manual patch-up (which always carries some risk).

> * Reorders the attributes of the following elements: `<rfc>`, `<author>`, `<date>`, `<xref>`, `<artwork>`, and `<svg>`. For instance, `<artwork type="svg" align="center">` is changed to `<artwork align="center" type="svg">`.

XML attribute order is insignificant, so this indeed really is no change.

> As there is no affect on output, this isn't really a bug. However, these changes can create noisy diffs, and some authors are sensitive to those.

Right.  authors really should:

* run this tool themselves before submitting
* switch on svg-id-cleanup in the YAML header to get this fix out right out of the normal kramdown-rfc process

> Could the script be updated to only make updates to ids and to leave the ordering of the XML attributes as is?

Indeed.  You should deliver this fix as a separate diff (commit) so that it doesn't get mixed up with your editorial changes.

The reason I don't really want to change the tool is that the code uses an XML library, both for some assurance of correctness and for convenience.  This library is doing the right thing by outputting a canonical attribute order (in this case what computer science people would call "lexicographical order").

Actually, it is somewhat weird that xml2rfc (which probably was generating this XML) generates XML with somewhat random attribute order.

(Of course, theoretically, people might submit manually generated XML, and then the output might also differ in insignificant whitespace.)

**Comment by ajeanmahoney** [comment] 2023-05-03 22:02
> The reason I don't really want to change the tool is that the code uses an XML library, both for some assurance of correctness and for convenience. This library is doing the right thing

Ack

> people might submit manually generated XML

RPC editors also make manual updates to the XML attributes. 

> Right. authors really should:
>
>  - run this tool themselves before submitting
>  - switch on svg-id-cleanup in the YAML header to get this fix out right out of the normal kramdown-rfc process

I see that the [SVG page](https://github.com/cabo/kramdown-rfc/wiki/SVG) already covers these points, but perhaps the section could mention that attributes may be reordered?

**Comment by cabo** [comment] 2023-05-03 22:05
I actually found some places in the XML library that could make keeping the order easier.  I'll explore this when back from travel...

**Comment by ajeanmahoney** [comment] 2023-05-15 13:02
Thanks! I've verified that it does not reorder attributes.

**Comment by cabo** [comment] 2023-07-13 13:05
This seems to work now, so I'm closing this.

Note that there are some other sources of duplicate IDs that could also be cleaned up.
This may require a strategy specific to the duplication's root cause, so I'm not attempting this now.

**Closed by cabo** 2023-07-13 13:05 UTC
